### ISSUE TITLE
Changing super admin's password in admin UI resets user's role

### ISSUE THREAD

**Issue by virtualzone** [seatsurfing/backend#156]
When changing a super admin's user in the Admin UI, the role drop down only shows "org admin" as maximum assignable role. When saving, not only the user being modified is not a super admin anymore, he/she is also degraded to a normal user.

**Comment by GabrieleV** [comment]
How can we assign superadmin role back to the admin ?

**Comment by virtualzone** [comment]
You can assign the super admin role back by setting ```role = 90``` to the corresponding user in table ```users```.
