### ISSUE TITLE
Language redirect problem in backend 1.14.1

### ISSUE THREAD

**Issue by farva7er** [seatsurfing/backend#171]
I'm experiencing a problem with language redirects very similar to https://github.com/seatsurfing/backend/issues/166.
I'm using latest docker images and compose file from here: https://hub.docker.com/r/seatsurfing/backend

Specifically, if I try to click on Administration button on /ui page, then it redirects to https://seatsurfing.mydomain.test/admin/dashboard/ which returns an error:
```
Get "https://seatsurfing.mydomain.test/admin/en/dashboard": tls: failed to verify certificate: x509: certificate signed by unknown authority
```
If I manually add "en" to the path like that: https://seatsurfing.mydomain.test/admin/en/dashboard/ then it works fine.

**Comment by virtualzone** [comment]
Hi @farva7er , unfortunately, the docker-compose.yml example at Docker Hub was outdated :-( I've just updated it.
Could you please try again with adding the new environment variable ```FRONTEND_URL``` at both the booking-ui and the admin-ui containers?
