### ISSUE TITLE
Whole day booking - remove time to be shown?

### ISSUE THREAD

**Issue by 0x3e4** [seatsurfing/backend#173]
Hey guys,

Now (for example):
Enter: 10/05/2023 **, 00:00**
Leave: 10/05/2023 **, 23:59**

Nice would be:
Enter: 10/05/2023
Leave: 10/05/2023

i even saw yesterday on a client that they was shown "24:00" instead of "00:00" (could be to some language formatting issues too) so would it be possible to completely remove the time when you enable "Allow bookings on a daily basis only"?

Currently running 1.13.8

Thanks a lot in advance!

**Comment by virtualzone** [comment]
Hi @0x3e4, please upgrade to v14, this should have been fixed in the meantime.

**Comment by xzxb** [comment]
@0x3e4 @virtualzone I started having the same issues with whole day booking then the formatting for "Today, Tomorrow, in X days" started bugging too. Running latest version. When turning daily booking off, today and tomorrow formats are correct but the in x days format is gone which is fine. However for daily booking it shows tomorrow as today. Am I doing something wrong?

![Screenshot 2023-10-31 061539](https://github.com/seatsurfing/backend/assets/34088774/20656eb9-778c-4a04-83cd-ef5907f09db7)
