### ISSUE TITLE
Keycloack integration

### ISSUE THREAD

**Issue by lifetooeasy** [seatsurfing/backend#176]
I am using docker compose to test `seatsurfing`. After configuring keycloack from the admin UI, I am redirected to login page but right after I become `The connection was reset` with the following error on the server:

```
example-server-1 |  2023-10-11 11-23-22 code exchange failed: Post "http://localhost:8081/realms/bob/protocol/openid-connect/token": dial tcp 127.0.0.1:8081: connect: connection refused
```
![Screenshot from 2023-10-11 11-23-22](https://github.com/seatsurfing/backend/assets/92575123/2f627bef-5de8-4481-9c51-e35521124542)

**Comment by fashberg** [comment]
Hi,
can seatsurfing-backend really access "http://localhost:8081/realms/bob/protocol/openid-connect/token"?

Looks on misconfigured keyclock, check https://keycloak.xxx.tld/auth/realms/bob/.well-known/openid-configuration
At "token_endpoint" you should read the tokenurl. That endpoint must be reachable for seatsurfing backend (container).

**Comment by lifetooeasy** [comment]
@fashberg thank you for looking into it. Actually, the redirect to keycloack works fine and I am able to authenticate:

![Screenshot from 2023-10-16 09-58-16](https://github.com/seatsurfing/backend/assets/92575123/62a1e912-3475-441b-9af4-7c67efd0dc4e)

seat surfing containers and keycloack are running in the same host with different ports.

For information, the configuration link is now at https://keycloak.xxx.tld/realms/bob/.well-known/openid-configuration and not at 
https://keycloak.xxx.tld/auth/realms/bob/.well-known/openid-configuration --> no /auth/

**Comment by fashberg** [comment]
You've wrote "I am using docker compose to test seatsurfing".
Imho: seatsurfing runs in its own container and each container has its own localhost. Docker basics.

From seatsurfing container you have to be able to reach keycloak container.
OpenId requires users (browsers) and app-server (seatsurfing) to talk to openid server. Backend has to access the token.

**Comment by lifetooeasy** [comment]
Same issue now backend and keycloack in different machines and different hostnames (not running on localhost) with token endpoint accessible from backend container. 
Login successful, redirect -> blank page.
