### ISSUE TITLE
Losing everything after restart container

### ISSUE THREAD

**Issue by lukasl96** [seatsurfing/backend#178]
Hi there,

each time I shut down the container and start it again, I lose every setting I made.
This Includes floorplans and seats

**Comment by lukasl96** [comment]
version: '3.7'

services:
  server:
    image: seatsurfing/backend
    restart: always
    networks:
      sql:
      http:
    ports:
      - 8080:8080
    environment:
      POSTGRES_URL: 'postgres://seatsurfing:DB-PW@db/seatsurfing?sslmode=disable'
      JWT_SIGNING_KEY: 'JWS-KEY'
      BOOKING_UI_BACKEND: 'booking-ui:3001'
      ADMIN_UI_BACKEND: 'admin-ui:3000'
      PUBLIC_URL: 'http://ll-docker-01:8080'
      FRONTEND_URL: 'http://ll-docker-01:8080'
  booking-ui:
    image: seatsurfing/booking-ui
    restart: always
    networks:
      http:
    environment:
      FRONTEND_URL: 'http://ll-docker-01:8080'
  admin-ui:
    image: seatsurfing/admin-ui
    restart: always
    networks:
      http:
    environment:
      FRONTEND_URL: 'http://ll-docker-01:8080'
  db:
    image: postgres:12
    restart: always
    networks:
      sql:
    volumes:
      - db:/opt/seatsurfing/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: DB-PW
      POSTGRES_USER: seatsurfing
      POSTGRES_DB: seatsurfing

volumes:
  db:

networks:
  sql:
  http:

**Comment by fashberg** [comment]
that's why:
![image](https://github.com/seatsurfing/backend/assets/3075214/b3e17a17-1811-4666-a245-79f55cbb8618)

**Comment by fashberg** [comment]
postgres stores inside the container at /var/lib/postgres/data. unchangeable path.
You persist the path /opt/seatsurfing/var/lib/postgres/data - but no one uses it.

If you don't want  to use volumes: local path on the left side:

```
volumes:
- /opt/seatsurfing/postgres:/var/lib/postgresql/data
```
and remove the volumes-section.

**Comment by lukasl96** [comment]
Sorry for the misconfiguration, I mixed up the syntax in a hurry.

Thank you for the quick replies, everything is now working as expected! :)
