### ISSUE TITLE
[Docker] Consider publishing docker images to a registry without rate-limiting

### ISSUE THREAD

**Issue by b2cc** [seatsurfing/backend#221]
Hello!

I'd like to ask if it would be possible to publish the docker images to an alternative repository than dockerhub as well.

We're running seatsurfing on a multi-node k8s cluster, and if the app gets restarted and multiple nodes start pulling containers the limit can be triggered rather quickly:
```
Failed to pull image "docker.io/seatsurfing/backend:latest": rpc error: code = Unknown desc = reading manifest latest in docker.io/seatsurfing/backend: 
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

Maybe `ghcr.io` and/or `quay.io` (free public tier) would be an option?
Thanks for your consideration!

**Comment by virtualzone** [comment]
Hi @b2cc , good idea! Version 1.16 added support for ghcr.io. I've already updated the Readme and the docs.

**Comment by b2cc** [comment]
Thanks, appreciated!
