### ISSUE TITLE
Feature: Admin can book all desks without limitation

### ISSUE THREAD

**Issue by FlorianDev** [seatsurfing/backend#235]
With the current version I am not able to book all desks at once when we want to use the space for e.g. events. I am also limited by the constraint set for "Users". 

It would be a great feature to be able to book desks without limitation as an admin.

Unfortunately my expertise in go programming is not really good, so I can't really develop it myself.

PS: Great Work! 🎇

Just a quick update:

I managed to bypass the booking limits by just set every booking done by an admin as valid, regardless of the time constraints set in the config.

Currently, it is only a workaround, but it would be great to have this kind of functionality officially.

**Comment by fashberg** [comment]
see #240

**Comment by IdanYaffe** [comment]
Hello @virtualzone 
This one can be closed as it was addressed here: https://github.com/seatsurfing/backend/pull/240
