### ISSUE TITLE
Problem with "Umlauts" in mail subject

### ISSUE THREAD

**Issue by urban-thinking** [seatsurfing/backend#237]
Hiya Guys,

there might be a problem in german password recovery email template ( server/res/email-resetpw_de.txt ). Most email servers in the wild might not allow special characters in subject and will reject those mails.

We have that exact problem, which produces a reject/bounce like so (Sample):

`May  9 11:08:18 servername postfix/smtp[740300]: 710783C7798: to=<user.name@vak.berlin.de>, relay=mx1.verwalt-berlin.de[141.15.34.10]:25, delay=0.2, delays=0.02/0.03/0.16/0, dsn=5.6.7, status=bounced (SMTPUTF8 is required, but was not offered by host mx1.verwalt-berlin.de[141.15.34.10])`

The problem seems to be the "Umlaut" in the subject line:

`Content-Type: text/plain; charset=UTF-8`
`Subject: ZurÃ¼cksetzen Ihres Seatsurfing-Kennworts`

Do you have any ideas or suggestions on this problem?

If we replace the subject line to `Subject: Zuruecksetzen Ihres Seatsurfing-Kennworts` the mail gets sent. We guess, a correct UTF-8 Umlaut like 'ü' will do as well.

kind regards
Emilio

**Comment by virtualzone** [comment]
Fixed in 1.19.3
