### ISSUE TITLE
Link based booking re-direct doesn't work with oauth2 provider

### ISSUE THREAD

**Issue by IdanYaffe** [seatsurfing/backend#265]
Hello,

This great feature doesn't work as expected due to an issue with the auth redirection:
https://github.com/seatsurfing/backend/pull/255

Steps to reproduce:

1. Use a seat booking link
2. You'll be redirected to authenticate (even if you're authenticated in another browser tab)
3. After auth, you will be redirected to the main app page instead of the seat booking pop-up

**Comment by virtualzone** [comment]
@olivierIllogika Can you look into this? Thanks!

**Comment by olivierIllogika** [comment]
@IdanYaffe can you provide the (domain anonymized):

1. booking link you're using
2. login url containing the "redir" parameter
3. final url you're redirected to (or not) after login

I've seen some weird stuff happening in the admin area editing page when adding spaces. Like duplicates and missing space id. If your bug suddenly disappear, try with a newly created space.

**Comment by olivierIllogika** [comment]
> 2. You'll be redirected to authenticate (even if you're authenticated in another browser tab)

Try to check the "Remember me" box when signing in. This persists the refreshToken to localStorage instead of just sessionStorage which is only scoped to the current tab.

**Comment by IdanYaffe** [comment]
Thanks for looking into this @olivierIllogika !

One important note is that I forgot to mention is that we're using Google workspaces as our SSO provider, so there's actually another redirect to Google as part of the authentication redirect.
**looks like this is the root cause as the redir works perfectly when logging in using a user & password**

1. https://<our base url>/ui/search?lid=91ce8dc5-1115-4dd5-84cd-a9b0aae34c70&sid=9554e11a-7138-4b91-a5ba-3653559737e3

2. https://<our base url>/ui/login?redir=%2Fsearch%3Flid%3D91ce8dc5-1115-4dd5-84cd-a9b0aae34c70%26sid%3D9554e11a-7138-4b91-a5ba-3653559737e3
(this has another redirect to Google)

3. https://<our base url>/ui/search
