### ISSUE TITLE
Disable areas or spaces

### ISSUE THREAD

**Issue by patrickbuec** [seatsurfing/backend#307]
Hello,
great project. I really like it.
Would it be possible to disable certain areas or spaces? For example, if a room or area is being renovated.
Thx

**Comment by fashberg** [comment]
Hey @patrickbuec ,

You can set global option `Don't restrict admins (bookings per user, duration, in advance)` and then your floorplan admins can block seats as long as required.
Already booked reservations can be moved to other seats by admins.

BR

**Comment by patrickbuec** [comment]
Hi @fashberg,

 that's a great idea! Thank you for the quick response.

Thx Patrick
