### ISSUE TITLE
Is it possible to update a floorplan map without redoing all the bookings?

### ISSUE THREAD

**Issue by gregfroese** [seatsurfing/backend#342]
I've got a number of desks setup and active assignments, and I need to mark one spot as permanently booked, or make a small change to the floorplan without having to rebuild the whole space and lose existing bookings.

Is there any way to:
1. Upload a modified image to replace the existing map?
2. Mark a spot as permanently booked (related issue #249)?

**Comment by virtualzone** [comment]
You can just upload a new version of your floor plan image without affecting existing spaces and bookings.

Marking a spot as unavailable is not possible yet, it's discussed in #249 .
