### ISSUE TITLE
Skip Two-Step-Login with one organization using one Auth Provider

### ISSUE THREAD

**Issue by virtualzone** [seatsurfing/backend#47]
At the moment, logging in using an Auth Provider (i.e. Keycloak) needs to go through two steps. 

Expectation: Avoid these two steps of login if there is only one organization with only one authorization provider.

**Comment by boostMNK** [comment]
Hi everybody,

I would like to share with you my solution - it is not perfect but it is a working transitional solution.
Maybe you could use it to implement a final solution.
I added the script to the index.html of the booking-ui.

```
var preflightUrl = "http://<yourSeatsurfingInstance>/auth/preflight";
var redirectToKcUrl = '';
httpRequest = new XMLHttpRequest();

if (!sessionStorage.getItem("runOnce")) {
    var existCondition = setInterval(function() {
        if (window.location.href.indexOf('login') != -1) {
                console.log('index of login: ' + window.location.href.indexOf('login'));
                fakePreflight();
                sessionStorage.setItem("runOnce", true);
        }
    }, 50); // check every 50 ms
}

function fakePreflight() {
    httpRequest.onreadystatechange = redirectToKc;
    httpRequest.open("POST", preflightUrl, true);
    httpRequest.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
    httpRequest.send(JSON.stringify({"email":"noreply@<youOrganization>.com"}));

    function redirectToKc() {
        if (this.readyState == 4 && this.status == 200) {
            var jsonResponse = JSON.parse(httpRequest.responseText);
            var redirectId = jsonResponse.authProviders[0].id;
            redirectToKcUrl = "http://<yourSeatsurfingInstance>/auth/"+redirectId+"/login/ui";
            console.log('send preflight request');
            window.location.href = redirectToKcUrl;
        } else {
            console.log('ERROR: fake preflight request.');
        }
    }
}
```

**Comment by virtualzone** [comment]
The improved login process for instances with one organisation and auth provides has been implemented as follows:

* When loading the login page, a REST call is made to /auth/singleorg
* The REST call returns a JSON object with information about the organization and its auth providers in case there is only one org; or HTTP 404 otherwise
* If the instance has one org only and there are auth providers, the login screen presents the list of auth providers directly without having to enter the username (email address) first.
* In case there is no user in the org requiring password authentication and there is only one auth provider, the user is redirected to the auth provider without having to choose an auth provider first.
