### ISSUE TITLE
Can only add one space to a floor plan

### ISSUE THREAD

**Issue by thr27** [seatsurfing/backend#48]
When I create a new area and upload a floor plan and then add multiple spaces, only one space gets saved.

You can add multiple spaces, but after saving and re-entering only the last space was stored.

I tested this on our installation and I can reproduce on your demo site: https://app.seatsurfing.app/admin/locations/b9d488a9-62e0-4550-82ca-e246a252585a

with firefox and chrome

**Comment by virtualzone** [comment]
Fixed in version 1.10.2
